### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by MaxHalford** [HAIRLAB/Pre_Surv_COVID_19#2]
Hey, is it possible the raw data? Or at least the version that was fed to the models? Currently the `data` folder is empty.

Keep up the good work.

**Comment by HAIRLAB** [comment]
please check here: https://www.nature.com/articles/s42256-020-0180-7


--
Ye Yuan
Professor, School of Artificial Intelligence and Automation,
State Key Lab of Digital Manufacturing Equipment and Technology,
Huazhong University of Science and Technology.
WWW: http://yy311.github.io.
-----Original Messages-----

**Comment by MaxHalford** [comment]
Thanks for the link. I found what I needed in the supplementary materials :)

**Comment by HAIRLAB** [comment]
great, please don't forget to give us a star:) 


--
Ye Yuan
Professor, School of Artificial Intelligence and Automation,
State Key Lab of Digital Manufacturing Equipment and Technology,
Huazhong University of Science and Technology.
WWW: http://yy311.github.io.
-----Original Messages-----
