### ISSUE TITLE
xlsx documents left out of data folder

### ISSUE THREAD

**Issue by miqueet** [HAIRLAB/Pre_Surv_COVID_19#3]
Hey All,

I noticed that the XLSX docs were left out of the data folder. Was that just for privacy reasons? I would like to be able to train this model with the same data to test this out and possibly put in my own data.

**Comment by HAIRLAB** [comment]
The data was available on Nature website. We just put it in. 


--
Ye Yuan
Professor, School of Artificial Intelligence and Automation,
State Key Lab of Digital Manufacturing Equipment and Technology,
Huazhong University of Science and Technology.
WWW: http://yy311.github.io.
-----Original Messages-----

**Comment by miqueet** [comment]
Thanks for the update. I'll go ahead and search for it.
